export const descs = {
  'QW-ACT-R1': 'HTML Page has a title',
  'QW-ACT-R2': 'HTML has lang attribute',
  'QW-ACT-R3': 'HTML lang and xml:lang match',
  'QW-ACT-R4': 'Meta-refresh no delay',
  'QW-ACT-R5': 'Validity of HTML Lang attribute',
  'QW-ACT-R6': 'Image button has accessible name',
  'QW-ACT-R7': 'Orientation of the page is not restricted using CSS transform property',
  'QW-ACT-R9': 'Links with identical accessible names have equivalent purpose',
  'QW-ACT-R10': 'iframe elements with identical accessible names have equivalent purpose',
  'QW-ACT-R11': 'Button has accessible name',
  'QW-ACT-R12': 'Link has accessible name',
  'QW-ACT-R13': 'Element with aria-hidden has no focusable content',
  'QW-ACT-R14': 'meta viewport does not prevent zoom',
  'QW-ACT-R15': 'audio or video has no audio that plays automatically',
  'QW-ACT-R16': 'Form control has accessible name',
  'QW-ACT-R17': 'Image has accessible name',
  'QW-ACT-R18': 'id attribute value is unique',
  'QW-ACT-R19': 'iframe element has accessible name',
  'QW-ACT-R20': 'role attribute has valid value',
  'QW-ACT-R21': 'svg element with explicit role has accessible name',
  'QW-ACT-R22': 'Element within body has valid lang attribute',
  'QW-ACT-R23': 'video element visual content has accessible alternative',
  'QW-ACT-R24': 'autocomplete attribute has valid value',
  'QW-ACT-R25': 'ARIA state or property is permitted',
  'QW-ACT-R26': 'video element auditory content has accessible alternative',
  'QW-ACT-R27': 'This rule checks that each aria- attribute specified is defined in ARIA 1.1.',
  'QW-ACT-R28': 'Element with role attribute has required states and properties',
  'QW-ACT-R29': 'Audio element content has text alternative',
  'QW-ACT-R30': 'Visible label is part of accessible name',
  'QW-ACT-R31': 'Video element visual-only content has accessible alternative',
  'QW-ACT-R32': 'video element visual content has strict accessible alternative',
  'QW-ACT-R33': 'ARIA required context role',
  'QW-ACT-R34': 'ARIA state or property has valid value',
  'QW-ACT-R35': 'Heading has accessible name',
  'QW-ACT-R36': 'Headers attribute specified on a cell refers to cells in the same table element',
  'QW-ACT-R37': 'Text has minimum contrast',
  'QW-ACT-R38': 'ARIA required owned elements',
  'QW-ACT-R39': 'All table header cells have assigned data cells',
  'QW-ACT-R40': 'Zoomed text node is not clipped with CSS overflow',
  'QW-ACT-R41': 'Error message describes invalid form field value',
  'QW-ACT-R42': 'Object element has non-empty accessible name',
  'QW-ACT-R43': 'Scrollable element is keyboard accessible',
  'QW-ACT-R44': 'Links with identical accessible names and context serve equivalent purpose',
  'QW-ACT-R48': 'Element marked as decorative is not exposed',
  'QW-ACT-R49': 'Audio or video that plays automatically has no audio that lasts more than 3 seconds',
  'QW-ACT-R50': 'Audio or video that plays automatically has a control mechanism',
  'QW-ACT-R51': 'video element visual-only content is media alternative for text',
  'QW-ACT-R52': 'video element visual-only content has description track',
  'QW-ACT-R53': 'video element visual-only content has transcript',
  'QW-ACT-R54': 'video element visual-only content has audio track alternative',
  'QW-ACT-R55': 'video element visual content has audio description',
  'QW-ACT-R56': 'video element content is media alternative for text',
  'QW-ACT-R57': 'video element visual content has description track',
  'QW-ACT-R58': 'audio element content has transcript',
  'QW-ACT-R59': 'audio element content is media alternative for text',
  'QW-ACT-R60': 'video element auditory content has captions',
  'QW-ACT-R61': 'video element visual content has transcript',
  'QW-ACT-R62': 'Element in sequential focus order has visible focus',
  'QW-ACT-R63': 'Document has a landmark with non-repeated content',
  'QW-ACT-R64': 'Document has heading for non-repeated content',
  'QW-ACT-R65': 'Element with presentational children has no focusable content',
  'QW-ACT-R66': 'Menuitem has non-empty accessible name',
  'QW-ACT-R67': 'Letter spacing in style attributes is not !important',
  'QW-ACT-R68': 'Line height in style attributes is not !important',
  'QW-ACT-R69': 'Word spacing in style attributes is not !important',
  'QW-ACT-R70': 'frame with negative tabindex has no interactive elements',
  'QW-ACT-R71': 'meta element has no refresh delay (no exception)',
  'QW-ACT-R72': 'First focusable element is link to non-repeated content',
  'QW-ACT-R73': 'Block of repeated content is collapsible',
  'QW-ACT-R74': 'Document has an instrument to move focus to non-repeated content',
  'QW-ACT-R75': 'Bypass Blocks of Repeated Content',
  'QW-ACT-R76': 'Text has enhanced contrast',
  'QW-ACT-R77': 'ARIA required ID references exist',
  'QW-WCAG-T1': 'Providing text alternatives for the area elements of image maps',
  'QW-WCAG-T2': 'Using caption elements to associate data table captions with data tables',
  'QW-WCAG-T3': 'Providing a description for groups of form controls using fieldset and legend elements',
  'QW-WCAG-T4': 'Using the summary attribute of the table element to give an overview of data tables',
  'QW-WCAG-T5': 'Using alt attributes on images used as submit buttons',
  'QW-WCAG-T6': 'Using both keyboard and other device-specific functions',
  'QW-WCAG-T7': 'Providing definitions for abbreviations by using the abbr element',
  'QW-WCAG-T8': 'Failure of Success Criterion 1.1.1 and 1.2.1 due to using text alternatives that are not alternatives',
  'QW-WCAG-T9': 'Organizing a page using headings',
  'QW-WCAG-T10': 'Combining adjacent image and text links for the same resource',
  'QW-WCAG-T11': 'Providing text alternatives on applet elements',
  'QW-WCAG-T12': 'Failure of Success Criterion 1.3.1 due to using th elements, caption elements, or non-empty summary attributes in layout tables',
  'QW-WCAG-T13': 'Failure of Success Criterion 2.2.2 due to using the blink element',
  'QW-WCAG-T14': 'Using id and headers attributes to associate data cells with header cells in data tables',
  'QW-WCAG-T15': 'Using the link element and navigation tools',
  'QW-WCAG-T16': 'Using HTML according to spec',
  'QW-WCAG-T17': 'Positioning labels to maximize predictability of relationships',
  'QW-WCAG-T18': 'Using table markup to present tabular information',
  'QW-WCAG-T19': 'Providing submit buttons',
  'QW-WCAG-T20': 'Supplementing link text with the title attribute',
  'QW-WCAG-T21': 'Failure of Success Criteria 2.4.4, 2.4.9 and 4.1.2 due to not providing an accessible name for an image which is the only content in a link',
  'QW-WCAG-T22': 'Failure of Success Criterion 3.2.1 and 3.2.5 due to opening a new window as soon as a new page is loaded',
  'QW-WCAG-T23': 'Adding a link at the top of each page that goes directly to the main content area',
  'QW-WCAG-T24': 'Failure of Success Criteria 2.1.1, 2.4.7, and 3.2.1 due to using script to remove focus when focus is received',
  'QW-WCAG-T25': 'Using the scope attribute to associate header cells and data cells in data tables',
  'QW-WCAG-T26': 'Failure of Success Criterion 4.1.2 due to using script to make div or span a user interface control in HTML without providing a role for the control',
  'QW-WCAG-T27': 'Failure of Success Criterion 1.4.8 due to using text that is justified (aligned to both the left and the right margins)',
  'QW-WCAG-T28': 'Using percent, em, names for font sizes',
  'QW-WCAG-T29': 'Specifying alignment either to the left or right in CSS',
  'QW-WCAG-T30': 'Failure of Success Criterion 2.2.2 due to using text-decoration:blink without a mechanism to stop it in less than five seconds',
  'QW-WCAG-T31': 'Failure of Success Criterion 1.4.3, 1.4.6 and 1.4.8 due to specifying foreground colors without specifying background colors or vice versa',
  'QW-WCAG-T32': 'Using ol, ul and dl for lists or groups of links'
};
